### ISSUE TITLE
Install system requirements on sharc to load pkg ks

### ISSUE THREAD

**Issue by annakrystalli** [angelaMc-chira/competition#1]
I've narrowed it down to the culprit package (I think!). [**`ks`**](https://cran.r-project.org/web/packages/ks/index.html) depends on package [**`rgl: 3D Visualization Using OpenGL`**](https://cran.r-project.org/web/packages/rgl/index.html) which has a number of System Requirements including **`OpenGL`**. 

Full sys reqs:

SystemRequirements: | OpenGL, GLU Library, XQuartz (on OSX), zlib (optional), libpng (>=1.2.9, optional), FreeType (optional), pandoc (>=1.13.1, needed for vignettes)
-- | --

@willfurnass, is this enough info to install what's necessary?

**Comment by willfurnass** [comment]
The OpenGL header files were installed on ShARC yesterday and the GLU header files should be installed later today.  You should then hopefully have all the essential libraries and header files you need, which I understand to be:

```
$ rpm -qa | egrep '^(mesa-libGL|libpng|zlib)'
mesa-libGL-17.0.1-6.20170307.el7.x86_64
mesa-libGLU-devel-9.0.0-4.el7.x86_64
zlib-1.2.7-17.el7.x86_64
libpng-1.5.13-7.el7_2.x86_64
zlib-devel-1.2.7-17.el7.x86_64
libpng-devel-1.5.13-7.el7_2.x86_64
zlib-1.2.7-17.el7.i686
libpng12-1.2.50-10.el7.x86_64
mesa-libGLU-9.0.0-4.el7.x86_64
mesa-libGL-devel-17.0.1-6.20170307.el7.x86_64
```

**Comment by annakrystalli** [comment]
Thanks @willfurnass mate!

**Comment by annakrystalli** [comment]
@angelaMc-chira I've just managed to install `ks` on sharc and it worked! Do you want to give it a go your end and let me know if you have problems?

**Comment by angelaMc-chira** [comment]
Cool, many thanks guys! I will give it a go today, fingers crossed!

**Comment by annakrystalli** [comment]
@angelaMc-chira PS go for sharc rather than iceberg

**Comment by angelaMc-chira** [comment]
I just tried now and I get the same errors; tried to install.packages 'ks' and 'picante' and installation of the packages has non-zero exist status (?) :(

**Comment by annakrystalli** [comment]
Hmmmmm very strange. I just managed to install both those packages. Is this on sharc? And did you try it through an interactive session? 

ie you need to log into sharc with (in my case):
`ssh -X ac1adk@sharc.shef.ac.uk`

then start an interactive session: 
`qrshx`

then load and launch R

`module load apps/R/3.4.0/gcc-4.8.5`
`R`

and then install packages
`install.packages("picante")`

you'll probably need to choose a mirror (`48`) and say yes to creating a user library.

**Comment by angelaMc-chira** [comment]
I did yep; hmm I'll just give it another go today :)

**Comment by willfurnass** [comment]
Are you both using the same C++ compiler and version of R?   R packages that compile source code when they are installed will be sensitive to the version of C++ compiler currently available (as the C++ compiler also provides a software library that may be referenced *after* your R package has been compiled and installed). 

In short, on SHARC I would make sure I load a specific compiler every time I load R:

```sh
module load dev/gcc/4.8.5
module load apps/R/3.4.0/gcc-4.8.5 
```

**Comment by angelaMc-chira** [comment]
Ok that might be the problem, because I just chose a random one. I will try with the one you mentioned, thanks!

**Comment by angelaMc-chira** [comment]
It works now, I've just used module load/dev/gcc/4.9.4 because I didn't have the option to choose 4.8.5 but it worked alright :) Thanks a lot for all the trouble. What I'll next is actually submit a job, now that the trial script is working fine.

Also let me know what you guys want to do next regarding using this as a case study for R-users using ShARC. Cheers!

**Comment by willfurnass** [comment]
@angelaMc-chira FYI GCC 4.8.5 is the default compiler i.e. the one you get if you don't explicitly load a version of GCC using `module load/dev/gcc/x.y.z`
